### ISSUE TITLE
Idea: merge classes from factory and attributes object

### ISSUE THREAD

**Issue by kyptin** [ungoldman/hyperaxe#14]
Awesome library! I'm loving the concise, functional approach.

I have a feature request. The following code:

```
const x = require('hyperaxe')
x('.c1')({class: 'c2'}, 'Hello').outerHTML
```

…yields the following HTML:

    <div class="c1" class="c2">Hello</div>

This is invalid HTML according to the [W3C Markup Validator](https://validator.w3.org/#validate_by_input).

It would be nice if classes from both places could be merged to produce the following valid HTML:

    <div class="c1 c2">Hello</div>

**Comment by ungoldman** [comment]
I agree! PR welcome.

**Comment by kyptin** [comment]
Hmm, after attempting a PR, I think I'm barking up the wrong tree. It's actually Hyperscript that has this behavior. This code:

```
const h = require('hyperscript')
h('.c1', {class: 'c2'}, 'Hello').outerHTML
```

…yields:

    '<div class="c1" class="c2">Hello</div>'

Hyperaxe isn't adding or taking away from what Hyperscript is doing. So I'll close this issue and start looking into Hyperscript instead. I may be back with a PR for bumping the Hyperscript version…

**Comment by ungoldman** [comment]
Sounds good! I'm happy you've found it useful, good luck in open source world.
