### ISSUE TITLE
Idea: treat false attribute values like null/undefined

### ISSUE THREAD

**Issue by kyptin** [ungoldman/hyperaxe#15]
Again, thanks for the library. You've made views fun again.

I noticed that when an attribute value is `null` or `undefined`, it's omitted entirely:

```
const x = require('hyperaxe')
x.input({name: null, id: undefined, type: 'a'}).outerHTML
// => '<input type="a">'
```

This is convenient (and maybe worth mentioning in the README as a feature) because I can have fewer conditionals in my code.

However, `false` is handled differently:

```
x.input({name: false, id: false, type: 'a'}).outerHTML
// => '<input name="false" id="false" type="a">'
```

In particular, this is a (very slight) pain point when handling the `required` attribute of inputs; for example:

```
const Input = (type, id, klass, name, value, required) => {
  const input = x(`input.form-control.${klass}`)
  const attrs = {type, name, value, id, required: required ? true : null}
  return input(attrs)
}
```

Notice the extra noise for the `required` attribute, which is needed so that a value of `false` omits the attribute entirely. (Per the HTML spec, any value for the `required` attribute means that the input is required, so the attribute must be omitted entirely.)

I can't think of a use case where the current behavior is convenient. My idea would technically be a breaking change, but (I think) worth it. Unless I'm missing a good use case.

**Comment by ungoldman** [comment]
I **think** this might be a coming from a lower level -- the underlying implementation of `hyperscript`, which is what gets used under the hood to create elements.

Please note this library hasn't been actively updated or maintained in over 3 years, so if you are brimming with ideas and want to run with them, you might be better off forking the project. There is very little source code to work with so should be easy to modify to your heart's content.

**Comment by kyptin** [comment]
Right, OK. After looking at the code, I agree that this must be a hyperscript thing. I'll close this.

Duly noted about forking, thanks.
