### ISSUE TITLE
What's the recommended way to add pre-existing HTML?

### ISSUE THREAD

**Issue by christianbundy** [ungoldman/hyperaxe#9]
I've got some Markdown I'd like to put in a document, but it looks like hyperaxe escapes it. Here's my current workaround:

```javascript
article({ innerHTML: markdownContent })
```

Is that the recommended way to deal with this use-case, or is there a better way to do it?

Thanks for all the work on this module, I'm really loving it so far. I owe you a beer @ungoldman.

**Comment by ungoldman** [comment]
That sounds like a good way to do it! This hasn't come up yet tbh, but it's definitely a valid use case.

hyperaxe delegates to [`hyperscript`](https://github.com/hyperhype/hyperscript) under the hood unless you substitute your own hyperscript implementation with `createFactory`, so I'd say do what works! Setting `innerHTML` directly seems fairly elegant and straightforward to me.

For reference here are a couple of related threads I found in the hyperscript issues:

https://github.com/hyperhype/hyperscript/issues/49
https://github.com/hyperhype/hyperscript/issues/66

In lieu of a beer, if you'd like to open a PR documenting how to add trusted / raw HTML content in the README to save the next person some time, that would be great!

**Comment by ungoldman** [comment]
Here's the equivalent in nanohtml, another hyperscript alternative, for reference:

https://github.com/choojs/nanohtml#interpolating-unescaped-html
